require:
  - rubocop-rails
  - rubocop-rspec

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

inherit_from: .rubocop_todo.yml
