require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'packaging/*'

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*.rb'
    - 'app/controllers/*_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/initializers/*.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'config/**/*'

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Style/FormatStringToken:
  Exclude:
    - 'lib/tasks/packaging.rake'

inherit_from: .rubocop_todo.yml
