sudo: false
language: ruby
cache: bundler
before_script:
  - RAILS_ENV=test bundle exec rails db:setup
jobs:
  include:
    - name: 'specs'
      script:
        - 'RAILS_ENV=test bundle exec rails db:setup'
        - 'bundle exec rails spec'
    - name: 'style'
      script:
        - 'bundle exec rubocop -v'
        - 'bundle exec rubocop'
